
package view;

import controller.ControladorProjeto;
import javax.swing.JOptionPane;
import model.Projeto;

/**
 *
 * @author renata
 */
public class TelaProjeto extends javax.swing.JDialog {
    
    ControladorProjeto controlador;
    

    public TelaProjeto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
         controlador = new ControladorProjeto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTelaProjeto = new javax.swing.JPanel();
        jLabelTituloTelaProjeto = new javax.swing.JLabel();
        jLabelSalvarTelaProjeto = new javax.swing.JLabel();
        jPanelProjeto = new javax.swing.JPanel();
        jLabelNomeProjeto = new javax.swing.JLabel();
        jTextFieldNomeProjeto = new javax.swing.JTextField();
        jLabelDescricaoProjeto = new javax.swing.JLabel();
        jScrollPaneDescricaoProjeto = new javax.swing.JScrollPane();
        jTextAreaDescricaoProjeto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 400));

        jPanelTelaProjeto.setBackground(new java.awt.Color(153, 204, 255));

        jLabelTituloTelaProjeto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTituloTelaProjeto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloTelaProjeto.setText("Projeto");

        jLabelSalvarTelaProjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check32.png"))); // NOI18N
        jLabelSalvarTelaProjeto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalvarTelaProjetoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTelaProjetoLayout = new javax.swing.GroupLayout(jPanelTelaProjeto);
        jPanelTelaProjeto.setLayout(jPanelTelaProjetoLayout);
        jPanelTelaProjetoLayout.setHorizontalGroup(
            jPanelTelaProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTelaProjetoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelTituloTelaProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSalvarTelaProjeto)
                .addGap(14, 14, 14))
        );
        jPanelTelaProjetoLayout.setVerticalGroup(
            jPanelTelaProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTituloTelaProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelSalvarTelaProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jPanelProjeto.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNomeProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNomeProjeto.setForeground(new java.awt.Color(71, 71, 71));
        jLabelNomeProjeto.setText("Nome");

        jTextFieldNomeProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldNomeProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeProjetoActionPerformed(evt);
            }
        });

        jLabelDescricaoProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelDescricaoProjeto.setForeground(new java.awt.Color(71, 71, 71));
        jLabelDescricaoProjeto.setText("Descrição");

        jTextAreaDescricaoProjeto.setColumns(20);
        jTextAreaDescricaoProjeto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextAreaDescricaoProjeto.setRows(5);
        jScrollPaneDescricaoProjeto.setViewportView(jTextAreaDescricaoProjeto);

        javax.swing.GroupLayout jPanelProjetoLayout = new javax.swing.GroupLayout(jPanelProjeto);
        jPanelProjeto.setLayout(jPanelProjetoLayout);
        jPanelProjetoLayout.setHorizontalGroup(
            jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProjetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPaneDescricaoProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addComponent(jLabelNomeProjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNomeProjeto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelProjetoLayout.createSequentialGroup()
                        .addComponent(jLabelDescricaoProjeto)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelProjetoLayout.setVerticalGroup(
            jPanelProjetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjetoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabelNomeProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDescricaoProjeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPaneDescricaoProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTelaProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTelaProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelProjeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeProjetoActionPerformed

    private void jLabelSalvarTelaProjetoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalvarTelaProjetoMouseClicked
        try {
            Projeto projeto = new Projeto();
            projeto.setNome(jTextFieldNomeProjeto.getText());
            projeto.setDescricao(jTextAreaDescricaoProjeto.getText());
            controlador.salvar(projeto);
            JOptionPane.showMessageDialog(rootPane, "Projeto salvo com sucesso");
        } catch (Exception e) {
           JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        this.dispose();        
    }//GEN-LAST:event_jLabelSalvarTelaProjetoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaProjeto dialog = new TelaProjeto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDescricaoProjeto;
    private javax.swing.JLabel jLabelNomeProjeto;
    private javax.swing.JLabel jLabelSalvarTelaProjeto;
    private javax.swing.JLabel jLabelTituloTelaProjeto;
    private javax.swing.JPanel jPanelProjeto;
    private javax.swing.JPanel jPanelTelaProjeto;
    private javax.swing.JScrollPane jScrollPaneDescricaoProjeto;
    private javax.swing.JTextArea jTextAreaDescricaoProjeto;
    private javax.swing.JTextField jTextFieldNomeProjeto;
    // End of variables declaration//GEN-END:variables
}
